contact_links:
  - name: 💬 Matrix Chat
    url: https://sequoia-social-ojrw.vercel.app/%23sequoiasupport%3Asocialserver.sequoiasupport.com/lobby
    about: Ask questions and talk to other Sequoia Social users and the maintainers
